### ISSUE TITLE
No 3.9.5 version in yum repo

### ISSUE THREAD

**Issue by rgralevsky** [lacework/lacework-agent-releases#4]
Agent version 3.9.5 isn't available in yum repo https://packages.lacework.net/RPMS/x86_64/lacework-prod.repo
The latest available is 3.8.2. Is that expected?

**Comment by cirego** [comment]
Hi @rgralevsky, prior to 5.0.0, we only published a single Lacework agent version at a time, even for users using `apt` and `yum`. With 5.0.0, we are now publishing multiple versions of the agent: https://support.lacework.com/hc/en-us/articles/4409769182611-Agent-Multiple-Version-Repositories.

However, we don't plan to publish older versions of the agent using this method. I'm going to mark this issue as closed for now. Please feel free to reopen if you're not happy with this resolution!
