### ISSUE TITLE
Make the Helm chart not use the latest tag by default

### ISSUE THREAD

**Issue by Matroxt** [lacework/lacework-agent-releases#5]
The `values.yaml` that is included in the Helm chart has `latest` as the default tag.
```yaml
image:
  tag: latest
```

It is pretty widely accepted that Helm charts shouldn't have `latest ` tag on them.
We wouldn't want one of the daemonsets to restart and pull a newer image without the cluster operators knowing about it.
It could introduce bugs, take more resources or a whole bunch of things, and that needs to be controlled by the operator.

If the operator wants to use the `latest` tag, that's on them, but it shouldn't be the default.

**Comment by cirego** [comment]
Hi @Matroxt, thanks again for the bug report! I opened lacework/helm-charts#4 to fix this in our public repo. I have also opened an internal PR to make sure that we fix this on our releases page (this Github repo) going forward (5.1 and onwards).
